### ISSUE TITLE
UNOCONV version

### ISSUE THREAD

**Issue by daneshka** [telemark/docker-node-unoconv#2]
Is it a good practice to not to define any unoconv version?

RUN DEBIAN_FRONTEND=noninteractive apt-get -t jessie-backports install -y **git unoconv** && apt-get clean

anytime that we create the image it may use another (newer) version of unoconv.

**Comment by zrrrzzt** [comment]
We use the version of unoconv from [Jessie backports](https://packages.debian.org/jessie-backports/text/unoconv) at the moment that version is 0.7-1.1~bpo8+1 and it has been that version for more than a year.

Your are of course right regarding the version might change. The way we solve this ourselves is to use the prebuilt version from [dockerhub](https://hub.docker.com/r/telemark/docker-node-unoconv) as base image.

If you want to lock the version we are open to PRs :-)

**Comment by daneshka** [comment]
Thank you for your response.
I'll make a PR. Let me know if it's ok or not. Thanks
