### ISSUE TITLE
Does unoconv use soffice ?

### ISSUE THREAD

**Issue by crapthings** [telemark/docker-node-unoconv#26]
100% cpu usage sometimes.

https://bugs.documentfoundation.org/show_bug.cgi?id=108246#c16

**Comment by zrrrzzt** [comment]
Yes. LibreOffice is responsible for the conversion of documents. [unoconv](https://github.com/dagwieers/unoconv) is the command line tool.

**Comment by crapthings** [comment]
there's a solution that solve cpu

https://bugs.documentfoundation.org/show_bug.cgi?id=108246#c19

but we haven't tried yet. will report later.

**Comment by zrrrzzt** [comment]
I think the version of LibreOffice used is this https://packages.debian.org/jessie-backports/libreoffice
